# This file contains the Project Configuration Parameters

# Random State
random_state: 100

# Verbose for Log Prints
verbose: True

# Dataset Path
dataset:
  # Training Dataset Path

  training_data_path: 'C:\Users\dell\Desktop\projects\Phillps_hac\Disease-Prediction-from-Symptoms-master\dataset\training_data.csv'

  # Test Dataset Path

  test_data_path: 'C:\Users\dell\Desktop\projects\Phillps_hac\Disease-Prediction-from-Symptoms-master\dataset\test_data.csv'

  # Validation Data Size for train_test_split
  validation_size: 0.20

# Model Parameters
model:

  # Decision Tree
  decision_tree:
    criterion: 'entropy'

  # Random Forest Classifier
  random_forest:
    n_estimators: 12

  # Gradient Boosting Classifier
  gradient_boost:
    n_estimators: 150
    criterion: 'friedman_mse'

# Model Save Path
model_save_path: 'C:\Users\dell\Desktop\projects\Phillps_hac'